# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
  # Pods for AuthenApp

end
